name: Build and Test Advent of Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        year: [2024]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT }}

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libgtest-dev

      # Step 3: Configure the build
      - name: Configure Build for Year ${{ matrix.year }}
        run: |
          cmake -S . -B build -DYEAR_TO_BUILD_MODE=${{ matrix.year }} -DDAY_TO_BUILD_MODE=all -DBUILD_TESTS_MODE=ON

      # Step 5: Build the project
      - name: Build Project for Year ${{ matrix.year }}
        run: cmake --build build

      # Step 6: Run tests
      - name: Run Tests for Year ${{ matrix.year }}
        run: ctest --test-dir build --output-on-failure
